### ISSUE TITLE
How to select a treeview item?

### ISSUE THREAD

**Issue by lanzorg** [mmarquee/ui-automation#1]
I have a treeview like the next one and I need to select the bold one.
Is it possible or not?
- Item#1
  - SubItem#1
    - **MyItem**
  - SubItem#2
  - SubItem#3
- Item#2
- Item#3

**Comment by mmarquee** [comment]
It is possible, I haven't got around to need to look at treeviews, but I might do that this week.

**Comment by mmarquee** [comment]
Note to self: 
https://msdn.microsoft.com/en-us/library/ms743706(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/ms743384(v=vs.110).aspx

**Comment by mmarquee** [comment]
This has been implemented, and is one of the examples in the documentation and also one of the example tests shows it in real usage
