### ISSUE TITLE
AutomationException Error: 0x80004002

### ISSUE THREAD

**Issue by camhart** [mmarquee/ui-automation#101]
Relevant Stacktrace:

```
mmarquee.automation.AutomationException: Error: 0x80004002
        at mmarquee.automation.BaseAutomation.getAutomationElementFromReference(BaseAutomation.java:66)
        at mmarquee.automation.UIAutomation.getElementFromHandle(UIAutomation.java:638)
```

Device is a Windows 7 (version 6.1) 64 bit machine running JDK 11.

Unfortunately I don't have access to the machine--just the crash reports.  Works on a few dozen other machines just fine.

**Comment by alroldan** [comment]
Hi @camhart, I know this question is not related to your topic but I've seen you are using this ui-automation wrapper on a Windows 7 machine. There is a non-resolved issue where @mmarquee says that is not possible to use the library on Windows 7 (https://github.com/mmarquee/ui-automation/issues/52) ¿How did you make it work?

**Comment by mmarquee** [comment]
I am going to close this issue as WIndows 7 is no longer supported by Microsoft, and we have never managed to work out what these Win7 issues were.
