### ISSUE TITLE
Re: QueryInterface(Guid.REFIID, PointerByReference) in the type Unknown

### ISSUE THREAD

**Issue by st970703** [mmarquee/ui-automation#11]
Hi there,

I recently downloaded the code from the repository "mmarquee/ui-automation" and recreated an Eclipse project. However, the method call to QueryInterface didn't seem to match and gave an error that "The method QueryInterface(Guid.REFIID, PointerByReference) in the type Unknown is not applicable for the arguments (Guid.GUID.ByValue, PointerByReference)".
I am using Neon.1a Release (4.6.1) and Java 1.8.
Can anyone give me some advice on how to solve this error?
Please find the screenshots attached.
![the method queryinterfac](https://cloud.githubusercontent.com/assets/20368209/22004328/88adfe8c-dcbf-11e6-9055-3df8cd142a42.png)
![properties foruiautomation](https://cloud.githubusercontent.com/assets/20368209/22004381/f38c6be4-dcbf-11e6-8b65-0b8e4b219210.JPG)

**Comment by markhumphreysjhc** [comment]
Are you using your own local version of the JNA library? If possible you should use the dependency in the pom.xml file to bring down the latest version - they recently release 4.3.0 and I've updated the project to use that release, rather than the snapshot that it depended on before.

**Comment by st970703** [comment]
Hi markhumphreysjhc,

I recreated the project in IntelliJ and now it works fine.
Thanks for your help.

**Comment by mmarquee** [comment]
Great, looks like something that Eclipse has done. I'll close the issue - if it is an Eclipse issues, it can be reopened again
Thanks
