### ISSUE TITLE
Change window transparency?

### ISSUE THREAD

**Issue by lanzorg** [mmarquee/ui-automation#2]
Some other ui automation wrappers/frameworks have this feature.
- https://www.autoitscript.com/autoit3/docs/functions/WinSetTrans.htm
- http://pywinauto.github.io/docs/code/pywinauto.controls.HwndWrapper.html?highlight=settransparency#pywinauto.controls.HwndWrapper.HwndWrapper.SetTransparency

It would be interresting to have it in ui-automation.

I don't know if it could help you but this is how to do it in C#:

```
using System;
using System.Diagnostics;
using System.Threading;
using System.Runtime.InteropServices;

namespace Demo
{
    class Program
    {
        [DllImport("user32.dll")]
        static extern IntPtr FindWindow(string lpClassName, string lpWindowName);

        [DllImport("user32.dll")]
        static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

        const int SW_HIDE = 0;
        const int SW_SHOW = 5;

        public static void Main(string[] args)
        {
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = @"C:\madVR\madHcCtrl.exe";
            psi.Arguments = "editLocalSettingsDontWait";
            Process.Start(psi);

            Thread.Sleep(1500);

            IntPtr hWnd = FindWindow("TFMadVRSettings", null);
            ShowWindow(hWnd, SW_HIDE);

            Console.Write("Press any key to continue...");
            Console.ReadKey(true);
        }
    }
}
```

**Comment by mmarquee** [comment]
I am still looking at this, unfortunately the com4j wrapper hasn't generated a working proxy for the getCurrentHandle, so I am looking at ways to get around this.

**Comment by mmarquee** [comment]
Oops, still open

**Comment by lanzorg** [comment]
Still no fix or workaround?

**Comment by mmarquee** [comment]
I have changed the underlying code to no longer use COM4J, but JNA only, so it should be possible to do this now. I will look at it next (hopefully)

**Comment by mmarquee** [comment]
OK, that was quite simple actually, so this is addressed by commit https://github.com/mmarquee/ui-automation/commit/8426184acfc13f804ad41425b395e841d1a937f7. I haven't pushed a release to sonartype yet as I have some other refactorings to do and I'll need to retest everything fully.

**Comment by lanzorg** [comment]
Thank you!
But why getTransparency() and not setTransparency()?

**Comment by mmarquee** [comment]
Urgh, typo, which I've corrected in the latest commit

**Comment by mmarquee** [comment]
This now works, so I am closing the issue, please reopen if there are any further issues
