### ISSUE TITLE
How to get the value from an custom element

### ISSUE THREAD

**Issue by john0703** [mmarquee/ui-automation#20]
Hi,
I'm trying to use mmarquee/ui-automation for a winform application autotest,  for the datagrid is an custom elemment, I want to get the item value "test123" to verify, could you give some help for this? thanks a lot.
catched the automation element by UISpy as below:
AutomationElement
  General Accessibility
    AccessKey:	""
    AcceleratorKey:	""
    IsKeyboardFocusable:	"False"
    LabeledBy:	"(null)"
    HelpText:	""

  State
    IsEnabled:	"True"
    HasKeyboardFocus:	"False"

  Identification
    ClassName:	""
    ControlType:	"ControlType.Custom"
    Culture:	"(null)"
    AutomationId:	""
    LocalizedControlType:	""
    Name:	"name row 0"

  Visibility
    BoundingRectangle:	"(356, 304, 226, 41)"
    ClickablePoint:	"(null)"
    IsOffscreen:	"False"

ControlPatterns
  Invoke

  Value
    Value:	"test123"
    IsReadOnly:	"True"

**Comment by mmarquee** [comment]
HI, I think there is not support yet for custom controls - as I had no examples to work from - Is it possible for you to make me an example so I can see what I need to add?

**Comment by john0703** [comment]
I'm not familiar with ms-uiautomation, hm... just want have an method to getvalue() like getname().. :) 
I have tried to use Text pattern getValue() method, but there have an error..not sure my usage is correct. :)
code:
PointerByReference pr = automation.CreateNamePropertyCondition("name row 0");	
			AutomationElement custom11 = window.getElement().findFirst(new TreeScope(TreeScope.Descendants),pr);
			
			Text pattern = new Text();
			PointerByReference unknown = custom11.getPattern(PatternID.Text.getValue());
            pattern.setPattern(unknown.getValue());
            System.out.println("value is:"+pattern.getText());
error msg:
at com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeObject(COMInvoker.java:42)
	at com.sun.jna.platform.win32.COM.Unknown.QueryInterface(Unknown.java:70)
	at mmarquee.automation.pattern.BasePattern.getRawPatternPointer(BasePattern.java:120)
	at mmarquee.automation.pattern.Text.getPattern(Text.java:54)
	at mmarquee.automation.pattern.Text.getText(Text.java:141)

**Comment by mmarquee** [comment]
I think this means it doesn't implement the Value pattern. I will have a look and see whether I can create a working example (seem to recall that some of the stuff in the Windows Explorer used Custom control types).

**Comment by john0703** [comment]
seem to use currentPropertyValue can get the Value.Value text of property, I have got the propertyid from https://msdn.microsoft.com/en-us/library/windows/desktop/ee671200(v=vs.85).aspx
but the result is null, why?? :)
AutomationElement custom11 = window.getElement().findFirst(new TreeScope(TreeScope.Descendants),pr);
custom11.currentPropertyValue(30045).toString();

**Comment by mmarquee** [comment]
The implementation of AutomationCustom is just a descendant of the AutomationContainer (which uses the ItemContainer pattern) - as this is the only example of Custom.Control I found - it seems that the control you are using is more than this, and needs a way of getting to the value - as from the example above there is a Value pattern implemented.

**Comment by mmarquee** [comment]
I've added a change to the code - not committed yet, to add a ValuePattern property

`private Value valuePattern;`

and then implement a get value method ..
  
  ```
/**
     * Gets the value text associated with this element
     * @return The value of the item
     * @throws AutomationException Something has gone wrong
     * @throws PatternNotFoundException Failed to find pattern
     */
    public String getValue() throws AutomationException, PatternNotFoundException {
        if (this.valuePattern == null) {
            this.valuePattern = this.getValuePattern();
        }

        return this.valuePattern.value();
    }
```

I can't find a way of testing this, so if you are using the source code rather than library, you could make the same changes and see if they work. If they do, then I'll write some unit tests for it and commit to the main code base.

**Comment by john0703** [comment]
thanks mmarquee,
I have added the code to custom control, but got an error as below:
code:
AutomationCustom ac = window.getCustom("name row 0");
System.out.println(ac.getValue());
error:
Exception in thread "main" java.lang.NullPointerException
	at com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeObject(COMInvoker.java:42)
	at com.sun.jna.platform.win32.COM.Unknown.QueryInterface(Unknown.java:70)
	at mmarquee.automation.pattern.BasePattern.getRawPatternPointer(BasePattern.java:75)
	at mmarquee.automation.pattern.Value.getPattern(Value.java:56)
	at mmarquee.automation.pattern.Value.value(Value.java:74)
	at mmarquee.automation.controls.AutomationCustom.getValue(AutomationCustom.java:66)
	at mmarquee.demo.TestADF.run(TestADF.java:135)
	at mmarquee.demo.MainADF.main(MainADF.java:23)

**Comment by john0703** [comment]
I debuged for this, found pattern.setPattern(unknown.getValue()) in AutomationBase can not set pattern.
using standard edit box works well.. the custom control failed.
could you give some suggestion?  really appreciated! mmarquee
![111](https://cloud.githubusercontent.com/assets/28800416/26304141/cdf21ae0-3f1c-11e7-8fc4-35803db6017d.png)

**Comment by john0703** [comment]
![33](https://cloud.githubusercontent.com/assets/28800416/26304349/81a20366-3f1d-11e7-9727-97912572b4f9.png)

**Comment by john0703** [comment]
I've created an example app for the custom control, How can I share it with you?

**Comment by john0703** [comment]
change the inspect tool, found the value saved in LegacyIAccessible.Value, using 30093 can get the value now, so close this issue. Thanks a lot.

**Comment by pradeep3594** [comment]
Hi mmarquee, 

Could you please share a sample code in java to read (any value) from mouse/key event? This will be helpful to start with.
