### ISSUE TITLE
Canalizer executorservice never gets shut down when run in scala-cucumber

### ISSUE THREAD

**Issue by mmarquee** [mmarquee/ui-automation#48]
For some reason the executorservice never gets shut down when this code is run in scala-cucumber, which makes test runs never complete.

I might have to remove this unless I can find a fix quickly

**Comment by mmarquee** [comment]
see https://stackoverflow.com/questions/7355378/what-is-the-exit-strategy-for-executors-newsinglethreadexecutor
and
https://stackoverflow.com/questions/22738912/executor-service-why-a-program-never-stops

**Comment by mmarquee** [comment]
I have backed out the code (actually just removed the calls to it), and the correct functionality has returned.
I will keep the issue open, as I think we might need to revisit it.

**Comment by mmarquee** [comment]
Flagged as being a 1.0 Release milestone

**Comment by mmarquee** [comment]
Trying to build some tests that make this happen, in the same way as our internal tests, so I can wok around it.

**Comment by mmarquee** [comment]
https://github.com/mmarquee/ui-automation/pull/55

**Comment by pbi-qfs** [comment]
Should be fixed with PR #57

**Comment by mmarquee** [comment]
This looks like it works as expected now, will close the issue and retest when there is an actual release.
