### ISSUE TITLE
UIAutomation.getInstance() never returns

### ISSUE THREAD

**Issue by dyorgio** [mmarquee/ui-automation#6]
The function UIAutomation.getInstance() frozen my application.
No error, no return, just show it on console:

```
ago 11, 2016 12:31:12 PM mmarquee.automation.UIAutomation <init>
INFORMAÃıES: Initializing ActiveX
ago 11, 2016 12:31:12 PM mmarquee.automation.UIAutomation <init>
INFORMAÃıES: Creating IUIAutomation instance
```

I'm using a  VM with Win10 to test my application.

**Comment by mmarquee** [comment]
Hi, can you make this happen with one of the demo programs - i.e. is it all the time, or with specific code?

If it is code you've  written, are you able to provide something for me to try and duplicate it?
Thanks

**Comment by dyorgio** [comment]
Hi,

The problems happens if you use a 32-bit JVM in a 64-bit Windows.

It happens with another dlls/libs too.

Maybe a check before initializing UIAutomation (if JVM and windows have the same arch) does the trick :).

I solved installing a 64 bits JVM on my windows VM. I also stop to use this lib in favor of direct OleACC calls, to my problem (GET URL from iexplorer, edge, firefox, chrome) Accessibility objects API was sufficient.

**Comment by mmarquee** [comment]
Closing the issue as it no longer active

**Comment by balahasavath** [comment]
> OleACC



> Hi,
> 
> The problems happens if you use a 32-bit JVM in a 64-bit Windows.
> 
> It happens with another dlls/libs too.
> 
> Maybe a check before initializing UIAutomation (if JVM and windows have the same arch) does the trick :).
> 
> I solved installing a 64 bits JVM on my windows VM. I also stop to use this lib in favor of direct OleACC calls, to my problem (GET URL from iexplorer, edge, firefox, chrome) Accessibility objects API was sufficient.

@dyorgio/ @mmarquee   -hi sorry did not mean to add here .. 
@dyorgio - you mentioned  "GET URL from iexplorer, edge, firefox, chrome) Accessibility objects API" - could you please help me few pointers/references to get Chrome URL /Edge URL using automation API in Java -please
