### ISSUE TITLE
Javadoc gen fails

### ISSUE THREAD

**Issue by sirajka** [mmarquee/ui-automation#87]
Javadoc goal failure.
Error in `mmarquee.automation.controls.LegacyAccessible.setValueFromIAccessible(final String value)`
Error: `incorrect use of inline tag @value`
Should be:
`    * @param value The string value`
Instead of 
`    * @value The string value`

Two other warnings:
Add missing `@param element` in
`mmarquee.automation.pattern.LegacyIAccessible.LegacyIAccessible(final AutomationElement element)`

Remove `<p>` and `</p>` in
`mmarquee.automation.uiautomation.IUIAutomationElement3.getCurrentIsPeripheral(Integer retVal)`

**Comment by mmarquee** [comment]
I have this fixed locally, will commit later today (hopefully)

**Comment by mmarquee** [comment]
I have now retested the builds and all looks OK in both the 'master' and 'develop' branches. Will close this issue
